Added new tutorial for `ESP32 circuit`
tscircuit/docs-old pull request #43
Opened 2024-12-03 17:36 UTC by AnasSarkiz

2024-12-03 17:45 UTC, AnasSarkiz commented
https://github.com/user-attachments/assets/7f00a9fd-ae46-4776-9dd7-39235a67e9b3

2024-12-04 00:29 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +  const C1 = useCapacitor("C1", { capacitance: "0F" }) //TDB
Are these really 0F?

2024-12-04 00:32 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +  name="U3" // Flash Memory
I wonder if we could get a manufacturer part number for this

2024-12-04 00:33 UTC, seveibar approved these changes
Note comments, need to check schematic against reference still but this is a well sized incremental step

2024-12-04 08:33 UTC, AnasSarkiz commented on tutorials/esp32-circuit.mdx
> +  const C1 = useCapacitor("C1", { capacitance: "0F" }) //TDB
<img width="1325" alt="Screenshot 2024-12-04 at 10 32 23 AM" src="https://github.com/user-attachments/assets/9c52c343-c742-4253-819e-31ebae54cdea">

2024-12-04 08:38 UTC, AnasSarkiz commented on tutorials/esp32-circuit.mdx
> +  name="U3" // Flash Memory
we already have
<img width="358" alt="Screenshot 2024-12-04 at 10 36 55 AM" src="https://github.com/user-attachments/assets/a83a7ff0-83eb-4da7-bc17-8b77e93eed5d">

2024-12-05 01:05 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +  const C1 = useCapacitor("C1", { capacitance: "0F" }) //TDB
oh i missed this...

2024-12-05 01:06 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +- ESP32 microcontroller
ESP32 is actually a family of microcontrollers, can you name the specific manufacturer part number? Goes for all the components here- they should have specific manufacturer part numbers

2024-12-05 01:08 UTC, seveibar requested changes
let's add specific part numbers

2024-12-05 01:08 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +import { useESP32 } from "@tsci/AnasSarkiz.ESP32"
this module should be named more specific to the actual ESP32 part number

2024-12-05 01:08 UTC, seveibar commented on tutorials/esp32-circuit.mdx
> +  const C1 = useCapacitor("C1", { capacitance: "0F" }) //TDB
yea it depends on the antenna, 0F for now is probably ok

2024-12-06 11:46 UTC, seveibar approved these changes

2024-12-06 11:46 UTC, merged